### ISSUE TITLE
I wonder why we don't see a mill-main update PR ?

### ISSUE THREAD

**Issue by lefou** [scala-steward-org/test-repo-2#102]
I would expect a PR to bump mill-main to 0.9.11, editing the `.mill-version` file.

**Comment by fthomas** [comment]
It is because I deleted the `build.sc` file in https://github.com/scala-steward-org/test-repo-2/commit/cfd515c14476d79799c65aaab2c3018e290067d7. It should update the version if that commit is reverted.
